"""reviewlog 加 state_before 快照列

Revision ID: 7c6690a1a73b
Revises: e01d07af597e
Create Date: 2026-07-11 18:37:10.115320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6690a1a73b'
down_revision: Union[str, Sequence[str], None] = 'e01d07af597e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_before', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewlog', schema=None) as batch_op:
        batch_op.drop_column('state_before')

    # ### end Alembic commands ###
