"""reviewlog 表 + block FSRS 字段

Revision ID: e01d07af597e
Revises: 47c8a8911bb9
Create Date: 2026-07-11 00:26:45.539799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01d07af597e'
down_revision: Union[str, Sequence[str], None] = '47c8a8911bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('interval_before', sa.Integer(), nullable=False),
    sa.Column('interval_after', sa.Integer(), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewlog_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewlog_reviewed_at'), ['reviewed_at'], unique=False)

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fsrs_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fsrs_step', sa.Integer(), nullable=True))

    # 历史回填：把每张已复习卡片的最近一次 last_review 转成一条日志
    # （quality=NULL 表示评分未知），保证热力图历史不断档
    op.execute(
        "INSERT INTO reviewlog (block_id, quality, reviewed_at, interval_before, interval_after) "
        "SELECT id, NULL, last_review, 0, interval FROM block WHERE last_review IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_column('fsrs_step')
        batch_op.drop_column('fsrs_state')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('stability')

    with op.batch_alter_table('reviewlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewlog_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_reviewlog_block_id'))

    op.drop_table('reviewlog')
    # ### end Alembic commands ###
